name: Record Radiko and store data
on:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: record radiko
        uses: docker://yyoshiki41/radigo
        with:
          entrypoitnt: rec
          args: -id=LFR -s=20230416010000
    
